import LangEng from '../../icons-components/language-eng';
import LangPort from '../../icons-components/language-port';

export const languageComponents = {
  eng: LangEng,
  port: LangPort,
};

export const languageLabels = {
  eng: 'ENGLISH',
  port: 'PORTUGAL',
};

type Translation = Record<string, string>;

export const langTranslations: Record<string, Translation> = {
  acorn: { port: 'a bolota' },
  apple: { port: 'a maçã' },
  arrow: { port: 'a flecha' },
  avocado: { port: 'o abacate' },
  backpack: { port: 'a mochila' },
  badger: { port: 'o texugo' },
  bag: { port: 'a mala' },
  ball: { port: 'a bola' },
  banana: { port: 'a banana' },
  bat: { port: 'a morcego' },
  bathtub: { port: 'a banheira' },
  bear: { port: 'o urso' },
  beaver: { port: 'o castor' },
  bee: { port: 'a abelha' },
  bike: { port: 'a bicicleta' },
  bikini: { port: 'o biquíni' },
  bird: { port: 'o pássaro' },
  blue: { port: 'azul' },
  boat: { port: 'a barca' },
  book: { port: 'o livro' },
  bottle: { port: 'a garrafa' },
  bowl: { port: 'a taça' },
  boy: { port: 'o rapaz' },
  branch: { port: 'o ramo' },
  bread: { port: 'o pão' },
  breakfast: { port: 'o pequeno-almoço' },
  brush: { port: 'o pincel' },
  bulb: { port: 'a lâmpada' },
  butterfly: { port: 'a borboleta' },
  cake: { port: 'o bolo' },
  candle: { port: 'a vela' },
  candy: { port: 'o rebuçado' },
  car: { port: 'o carro' },
  cat: { port: 'o gato' },
  chair: { port: 'a cadeira' },
  clock: { port: 'o relógio' },
  cloud: { port: 'a nuvem' },
  coffee: { port: 'o café' },
  computermouse: { port: 'o mouse de computador' },
  coral: { port: 'o coral' },
  cow: { port: 'a vaca' },
  crab: { port: 'o caranguejo' },
  cream: { port: 'o creme' },
  cup: { port: 'a chávena' },
  cuttingboard: { port: 'a tábua de corte' },
  deer: { port: 'o veado' },
  display: { port: 'o ecrã (de computador)' },
  dolphin: { port: 'o delfim' },
  dragonfly: { port: 'a libélula' },
  drop: { port: 'a gota' },
  earth: { port: 'a terra' },
  elephant: { port: 'o elefante' },
  festoon: { port: 'as luzes ' },
  fire: { port: 'o fogo' },
  fish: { port: 'o peixe' },
  flower: { port: 'a flor' },
  folder: { port: 'a pasta' },
  fork: { port: 'o garfo' },
  fox: { port: 'a raposa' },
  giraff: { port: 'a girafa' },
  girl: { port: 'a rapariga' },
  glass: { port: 'o vidro' },
  glasses: { port: 'os óculos' },
  grass: { port: 'a erva' },
  green: { port: 'verde' },
  grey: { port: 'cinzento' },
  hand: { port: 'a mão' },
  hare: { port: 'a lebre' },
  hat: { port: 'o chapéu' },
  headphones: { port: 'os fones' },
  hedgehog: { port: 'o ouriço' },
  hippo: { port: 'o hipopótamo' },
  house: { port: 'a casa' },
  icefloe: { port: 'o gelo' },
  jam: { port: 'a geleia' },
  jellyfish: { port: 'a medusa' },
  juice: { port: 'o sumo' },
  key: { port: 'a chave' },
  killerwhale: { port: 'a orca' },
  knife: { port: 'a faca' },
  koala: { port: 'o coala' },
  ladybug: { port: 'a joaninha' },
  lamp: { port: 'o candeeiro' },
  leaf: { port: 'a folha' },
  lemonade: { port: 'a limonada' },
  letter: { port: 'a carta' },
  lifebuoy: { port: 'tábua de salvação' },
  lighter: { port: 'o isqueiro' },
  lighthouse: { port: 'o farol' },
  lion: { port: 'o leão' },
  lobster: { port: 'a lagosta' },
  lock: { port: 'a fechadura (da porta)' },
  lollipop: { port: 'o caramelo' },
  microwave: { port: 'a micro-ondas' },
  moon: { port: 'a lua' },
  moose: { port: 'o alce' },
  mountain: { port: 'a montanha' },
  mushroom: { port: 'o cogumelo' },
  mussel: { port: 'o mexilhão' },
  needle: { port: 'a agulha' },
  nut: { port: 'a noz' },
  octopus: { port: 'o polvo' },
  orange: { port: 'a laranja' },
  owl: { port: 'a coruja' },
  pancakes: { port: 'as panquecas' },
  paper: { port: 'o papel' },
  pear: { port: 'a pêra' },
  pen: { port: 'a caneta' },
  pencil: { port: 'o lápis' },
  penguin: { port: 'o pinguim' },
  pepper: { port: 'a pimenta' },
  percent: { port: 'a percentagem' },
  phone: { port: 'o telefone' },
  picture: { port: 'a imagem' },
  pig: { port: 'o porco' },
  pine: { port: 'o pinheiro' },
  plane: { port: 'o avião' },
  polarbear: { port: 'o urso-branco' },
  popcorn: { port: 'a pipoca' },
  pot: { port: 'a panela' },
  present: { port: 'o presente' },
  rabbit: { port: 'o coelho' },
  raccoon: { port: 'o guaxinim' },
  rain: { port: 'a chuva' },
  red: { port: 'vermelho' },
  rollers: { port: 'os patins' },
  rollingpin: { port: 'rolo de massa' },
  ruler: { port: 'a régua' },
  scissors: { port: 'a tesoura' },
  seagull: { port: 'a gaivota' },
  seahorse: { port: 'o cavalo-marinho' },
  seal: { port: 'a foca' },
  sheep: { port: 'a ovelha' },
  shell: { port: 'a concha' },
  shoppingcart: { port: 'o carrinho de compras' },
  slippers: { port: 'os chinelos' },
  snail: { port: 'o caracol' },
  soap: { port: 'o sabonete' },
  sock: { port: 'a meia' },
  spatula: { port: 'a espátula' },
  spider: { port: 'a aranha' },
  spoon: { port: 'a colher' },
  squirrel: { port: 'o esquilo' },
  star: { port: 'a estrela' },
  stingray: { port: 'a raia' },
  stove: { port: 'o fogão' },
  strawberry: { port: 'o morango' },
  stump: { port: 'o cepo' },
  submarine: { port: 'o submarino' },
  sun: { port: 'o sol' },
  surf: { port: 'a surf' },
  tshirt: { port: 'a camiseta ' },
  tea: { port: 'o chá' },
  teapot: { port: 'o bule' },
  tiger: { port: 'o tigre' },
  trace: { port: 'a pegada' },
  tree: { port: 'a árvore' },
  turtle: { port: 'a tartaruga' },
  umbrella: { port: 'o guarda-chuva' },
  walrus: { port: 'a morsa' },
  wave: { port: 'a onda' },
  whale: { port: 'a baleia' },
  white: { port: 'branco' },
  window: { port: 'a janela' },
  yellow: { port: 'amarelo' },
};
