name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: deploy to staging
    runs-on: windows-latest
    env:
      CI: false
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages'
          path: build
      - name: Deploy to GitHup pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: 'github-pages'
